from collections.abc import Mapping, Sequence, Set
import enum


class BufferKind(enum.Enum):
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    WORKSPACE = 0

    CONSTANT = 1

    INPUT = 2

    OUTPUT = 3

    @property
    def is_io(self) -> bool: ...

    def __hash__(self) -> int: ...

class Allocation:
    def __init__(self, id: int | str, size: int, start: int | Sequence[int], end: int | Sequence[int], offset: int | None = None, kind: BufferKind | None = None) -> None: ...

    @property
    def id(self) -> int | str: ...

    @property
    def size(self) -> int: ...

    @property
    def start(self, /) -> int | tuple[int, ...]: ...

    @property
    def end(self, /) -> int | tuple[int, ...]: ...

    @property
    def dim(self) -> int: ...

    @property
    def offset(self) -> int | None: ...

    @property
    def kind(self) -> BufferKind | None: ...

    @property
    def is_allocated(self) -> bool: ...

    @property
    def duration(self) -> int: ...

    @property
    def height(self) -> int | None: ...

    @property
    def area(self) -> int: ...

    def overlaps_temporally(self, other: Allocation) -> bool: ...

    def overlaps_spatially(self, other: Allocation) -> bool: ...

    def overlaps(self, other: Allocation) -> bool: ...

    def with_offset(self, offset: int) -> Allocation: ...

    def with_kind(self, kind: BufferKind) -> Allocation: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Allocation, /) -> bool: ...

    def __hash__(self) -> int: ...

    def __getstate__(self) -> tuple[int | str, int, int | list[int], int | list[int], int | None, BufferKind | None]: ...

    def __setstate__(self, arg: tuple[int | str, int, int | Sequence[int], int | Sequence[int], int | None, BufferKind | None], /) -> None: ...

def compute_temporal_overlaps(allocations: Sequence[Allocation]) -> dict[int | str, set[int | str]]: ...

def compute_conflict_degrees(allocations: Sequence[Allocation]) -> list[int]: ...

def try_linearize(allocations: Sequence[Allocation], work_budget: int = 18446744073709551615) -> list[Allocation] | None: ...

DEFAULT_WORK_BUDGET: int = 100000000

DEFAULT_CLOSURE_CAP: int = 16384

def antichain_pressure(allocations: Sequence[Allocation], work_budget: int = 18446744073709551615) -> int: ...

def closure_pressure(allocations: Sequence[Allocation], closure_cap: int = 16384) -> int | None: ...

def per_allocation_antichain_pressure(allocations: Sequence[Allocation], work_budget: int = 18446744073709551615) -> list[int]: ...

def per_allocation_closure_pressure(allocations: Sequence[Allocation], closure_cap: int = 16384) -> list[int] | None: ...

def per_allocation_placement_pressure(allocations: Sequence[Allocation], clique_cap: bool = False) -> list[int]: ...

def first_fit_place(allocations: Sequence[Allocation], overlaps: Mapping[int | str, Set[int | str]]) -> list[Allocation]: ...

class FirstFitPlacer:
    def __init__(self, allocations: Sequence[Allocation]) -> None: ...

    def evaluate(self, order: Sequence[int]) -> int: ...

    def place(self, order: Sequence[int]) -> list[Allocation]: ...

    @property
    def overlaps(self) -> dict[int | str, set[int | str]]: ...

class GreedyAllocatorCpp:
    def __init__(self) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: GreedyAllocatorCpp, /) -> bool: ...

    def __hash__(self) -> int: ...

class OmniAllocatorCpp:
    def __init__(self) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: OmniAllocatorCpp, /) -> bool: ...

    def __hash__(self) -> int: ...

class BestFitAllocatorCpp:
    def __init__(self) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: BestFitAllocatorCpp, /) -> bool: ...

    def __hash__(self) -> int: ...

class SimulatedAnnealingConfig:
    def __init__(self, seed: int = 42, max_iterations: int = 3000, initial_temperature: float = 3.0, cooling_rate: float = 0.998, timeout: float = 3.0) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def initial_temperature(self) -> float: ...

    @initial_temperature.setter
    def initial_temperature(self, arg: float, /) -> None: ...

    @property
    def cooling_rate(self) -> float: ...

    @cooling_rate.setter
    def cooling_rate(self, arg: float, /) -> None: ...

    @property
    def timeout(self) -> float: ...

    @timeout.setter
    def timeout(self, arg: float, /) -> None: ...

class SimulatedAnnealingAllocatorCpp:
    def __init__(self, config: SimulatedAnnealingConfig = ...) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

class TabuSearchConfig:
    def __init__(self, seed: int = 42, max_iterations: int = 500, neighborhood_size: int = 20, tabu_tenure: int = 15, timeout: float = 3.0) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def neighborhood_size(self) -> int: ...

    @neighborhood_size.setter
    def neighborhood_size(self, arg: int, /) -> None: ...

    @property
    def tabu_tenure(self) -> int: ...

    @tabu_tenure.setter
    def tabu_tenure(self, arg: int, /) -> None: ...

    @property
    def timeout(self) -> float: ...

    @timeout.setter
    def timeout(self, arg: float, /) -> None: ...

class TabuSearchAllocatorCpp:
    def __init__(self, config: TabuSearchConfig = ...) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

class TelamallocConfig:
    def __init__(self, seed: int = 42, max_backtracks: int = 10000, timeout: float = 3.0) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def max_backtracks(self) -> int: ...

    @max_backtracks.setter
    def max_backtracks(self, arg: int, /) -> None: ...

    @property
    def timeout(self) -> float: ...

    @timeout.setter
    def timeout(self, arg: float, /) -> None: ...

class TelamallocAllocatorCpp:
    def __init__(self, config: TelamallocConfig = ...) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

class SearchOptions:
    def __init__(self, canonical: bool = True, dominance: bool = True, floor_inference: bool = True, monotonic_floor: bool = True, decompose: bool = True) -> None: ...

    @property
    def canonical(self) -> bool: ...

    @canonical.setter
    def canonical(self, arg: bool, /) -> None: ...

    @property
    def dominance(self) -> bool: ...

    @dominance.setter
    def dominance(self, arg: bool, /) -> None: ...

    @property
    def floor_inference(self) -> bool: ...

    @floor_inference.setter
    def floor_inference(self, arg: bool, /) -> None: ...

    @property
    def monotonic_floor(self) -> bool: ...

    @monotonic_floor.setter
    def monotonic_floor(self, arg: bool, /) -> None: ...

    @property
    def decompose(self) -> bool: ...

    @decompose.setter
    def decompose(self, arg: bool, /) -> None: ...

class Partition:
    @staticmethod
    def from_allocations(allocations: Sequence[Allocation]) -> Partition: ...

    def greedy_pack(self, heuristic: str) -> Solution: ...

    def reorder(self, heuristic: str) -> Partition: ...

    def with_bound(self, bound: int) -> Partition: ...

    @property
    def lower_bound(self) -> int: ...

class Solution:
    @property
    def allocations(self) -> list[Allocation]: ...

    @property
    def offsets(self) -> list[int]: ...

    @property
    def height(self) -> int: ...

def greedy_many(partition: Partition, heuristics: Sequence[str], timeout: float, num_threads: int) -> Solution: ...

def solve_many(partitions: Sequence[Partition], node_limit: int, timeout: float, best_bound: int, options: SearchOptions, num_threads: int) -> Solution | None: ...
