from collections.abc import Sequence
import enum


class AllocationKind(enum.Enum):
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    WORKSPACE = 0

    CONSTANT = 1

    INPUT = 2

    OUTPUT = 3

    @property
    def is_io(self) -> bool: ...

    def __hash__(self) -> int: ...

class Allocation:
    def __init__(self, id: int | str, size: int, start: int | Sequence[int], end: int | Sequence[int], offset: int | None = None, kind: AllocationKind | None = None) -> None: ...

    @property
    def id(self) -> int | str: ...

    @property
    def size(self) -> int: ...

    @property
    def start(self, /) -> int | tuple[int, ...]: ...

    @property
    def end(self, /) -> int | tuple[int, ...]: ...

    @property
    def dim(self) -> int: ...

    @property
    def offset(self) -> int | None: ...

    @property
    def kind(self) -> AllocationKind | None: ...

    @property
    def is_allocated(self) -> bool: ...

    @property
    def duration(self) -> int: ...

    @property
    def height(self) -> int | None: ...

    @property
    def area(self) -> int: ...

    def conflicts_with(self, other: Allocation) -> bool: ...

    def overlaps_spatially(self, other: Allocation) -> bool: ...

    def overlaps(self, other: Allocation) -> bool: ...

    def with_offset(self, offset: int) -> Allocation: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Allocation, /) -> bool: ...

    def __hash__(self) -> int: ...

    def __getstate__(self) -> tuple[int | str, int, int | tuple[int, ...], int | tuple[int, ...], int | None, AllocationKind | None]: ...

    def __setstate__(self, arg: tuple[int | str, int, int | Sequence[int], int | Sequence[int], int | None, AllocationKind | None], /) -> None: ...

def conflicts(allocations: Sequence[Allocation], work_budget: int | None) -> dict[int | str, set[int | str]]: ...

def conflict_degrees(allocations: Sequence[Allocation], work_budget: int | None) -> list[int]: ...

def try_linearize(allocations: Sequence[Allocation], work_budget: int | None) -> list[Allocation] | None: ...

def antichain_pressure(allocations: Sequence[Allocation], work_budget: int | None) -> int: ...

def closure_pressure(allocations: Sequence[Allocation], closure_cap: int | None) -> int: ...

def antichain_pressure_per_allocation(allocations: Sequence[Allocation], work_budget: int | None) -> list[int]: ...

def closure_pressure_per_allocation(allocations: Sequence[Allocation], closure_cap: int | None) -> list[int]: ...

def placement_pressure_per_allocation(allocations: Sequence[Allocation], work_budget: int | None) -> list[int]: ...

def first_fit_place(allocations: Sequence[Allocation]) -> list[Allocation]: ...

class FirstFitPlacer:
    def __init__(self, allocations: Sequence[Allocation]) -> None: ...

    def peak(self, order: Sequence[int]) -> int: ...

    def place(self, order: Sequence[int]) -> list[Allocation]: ...

    @property
    def conflicts(self) -> dict[int | str, set[int | str]]: ...

def best_fit_place(allocations: Sequence[Allocation]) -> list[Allocation]: ...

def omni_place(allocations: Sequence[Allocation], linearize_budget: int | None) -> list[Allocation]: ...

def simulated_annealing_place(allocations: Sequence[Allocation], seed: int, max_iterations: int, initial_temperature: float, cooling_rate: float, timeout: float | None) -> list[Allocation]: ...

def tabu_search_place(allocations: Sequence[Allocation], seed: int, max_iterations: int, neighborhood_size: int, tabu_tenure: int, timeout: float | None) -> list[Allocation]: ...

def telamalloc_place(allocations: Sequence[Allocation], seed: int, max_backtracks: int, timeout: float | None) -> list[Allocation]: ...

class Partition:
    @staticmethod
    def from_allocations(allocations: Sequence[Allocation]) -> Partition: ...

    def reorder(self, heuristic: str) -> Partition: ...

    def with_bound(self, bound: int) -> Partition: ...

    @property
    def lower_bound(self) -> int: ...

class Solution:
    @property
    def allocations(self) -> list[Allocation]: ...

    @property
    def peak(self) -> int: ...

def greedy_pack_portfolio(partition: Partition, heuristics: Sequence[str], timeout: float | None, num_threads: int) -> Solution: ...

def try_solve_many(partitions: Sequence[Partition], best_bound: int, max_nodes: int | None, canonical: bool, dominance: bool, floor_inference: bool, monotonic_floor: bool, decompose: bool, timeout: float | None, num_threads: int) -> Solution | None: ...
